2017-05-02 11:05:58 luadriver.py methed:creatLuaDriver line:39 INFO - creat luadriver
2017-05-02 11:06:19 luadriver.py methed:creatLuaDriver line:45 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appiumcenter\luadriver.py", line 42, in creatLuaDriver
    __global_luadriver=webdriver.Remote(luaurl, self.capabilities)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appium\webdriver\webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 185, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 249, in execute
    self.error_handler.check_response(response)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\errorhandler.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: A new session could not be created. (Original error: TestBundle quit before it successfully launched)


2017-05-02 11:06:19 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:06:19 luadriver.py methed:closeLuadriver line:48 INFO - close luadriver
2017-05-02 11:06:20 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-05-02 11:06:36 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-05-02 11:06:36 luadriver.py methed:creatLuaDriver line:39 INFO - creat luadriver
2017-05-02 11:07:52 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-05-02 11:08:17 luadriver.py methed:creatLuaDriver line:45 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appiumcenter\luadriver.py", line 42, in creatLuaDriver
    __global_luadriver=webdriver.Remote(luaurl, self.capabilities)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appium\webdriver\webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 185, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 249, in execute
    self.error_handler.check_response(response)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\errorhandler.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: A new session could not be created. (Original error: TestBundle quit before it successfully launched)


2017-05-02 11:08:17 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:08:17 luadriver.py methed:closeLuadriver line:48 INFO - close luadriver
2017-05-02 11:08:17 luadriver.py methed:creatLuaDriver line:39 INFO - creat luadriver
2017-05-02 11:08:45 luadriver.py methed:creatLuaDriver line:45 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appiumcenter\luadriver.py", line 42, in creatLuaDriver
    __global_luadriver=webdriver.Remote(luaurl, self.capabilities)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appium\webdriver\webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 185, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 249, in execute
    self.error_handler.check_response(response)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\errorhandler.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: A new session could not be created. (Original error: TestBundle quit before it successfully launched)


2017-05-02 11:08:45 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:08:45 luadriver.py methed:closeLuadriver line:48 INFO - close luadriver
2017-05-02 11:08:45 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-05-02 11:11:21 nativedriver.py methed:creatNativeDriver line:42 ERROR - [Errno 10054] 
2017-05-02 11:11:21 nativedriver.py methed:creatNativeDriver line:42 ERROR - [Errno 10054] 
2017-05-02 11:11:21 nativedriver.py methed:creatNativeDriver line:43 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appiumcenter\nativedriver.py", line 39, in creatNativeDriver
    __global_nativedriver=webdriver.Remote(nativeurl, self.capabilities)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appium\webdriver\webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 185, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 247, in execute
    response = self.command_executor.execute(driver_command, params)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\remote_connection.py", line 466, in execute
    return self._request(command_info[0], url, body=data)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\remote_connection.py", line 527, in _request
    resp = opener.open(request, timeout=self._timeout)
  File "D:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "D:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "D:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "D:\Python27\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "D:\Python27\lib\urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "D:\Python27\lib\httplib.py", line 1136, in getresponse
    response.begin()
  File "D:\Python27\lib\httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "D:\Python27\lib\httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "D:\Python27\lib\socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 10054] 

2017-05-02 11:11:21 nativedriver.py methed:creatNativeDriver line:43 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appiumcenter\nativedriver.py", line 39, in creatNativeDriver
    __global_nativedriver=webdriver.Remote(nativeurl, self.capabilities)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appium\webdriver\webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 185, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 247, in execute
    response = self.command_executor.execute(driver_command, params)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\remote_connection.py", line 466, in execute
    return self._request(command_info[0], url, body=data)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\remote_connection.py", line 527, in _request
    resp = opener.open(request, timeout=self._timeout)
  File "D:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "D:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "D:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "D:\Python27\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "D:\Python27\lib\urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "D:\Python27\lib\httplib.py", line 1136, in getresponse
    response.begin()
  File "D:\Python27\lib\httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "D:\Python27\lib\httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "D:\Python27\lib\socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 10054] 

2017-05-02 11:11:21 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-05-02 11:11:21 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-05-02 11:11:21 nativedriver.py methed:getNativeDriver line:61 ERROR - global name '_NativeDriver__global_nativedriver' is not defined
2017-05-02 11:11:21 nativedriver.py methed:getNativeDriver line:62 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appiumcenter\nativedriver.py", line 58, in getNativeDriver
    return __global_nativedriver
NameError: global name '_NativeDriver__global_nativedriver' is not defined

2017-05-02 11:11:21 luadriver.py methed:creatLuaDriver line:39 INFO - creat luadriver
2017-05-02 11:11:22 remote_connection.py methed:__init__ line:222 INFO - Could not get IP address for host: 127.0.0.1
2017-05-02 11:11:22 remote_connection.py methed:__init__ line:222 INFO - Could not get IP address for host: 127.0.0.1
2017-05-02 11:11:23 luadriver.py methed:creatLuaDriver line:45 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appiumcenter\luadriver.py", line 42, in creatLuaDriver
    __global_luadriver=webdriver.Remote(luaurl, self.capabilities)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appium\webdriver\webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 185, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 247, in execute
    response = self.command_executor.execute(driver_command, params)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\remote_connection.py", line 466, in execute
    return self._request(command_info[0], url, body=data)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\remote_connection.py", line 527, in _request
    resp = opener.open(request, timeout=self._timeout)
  File "D:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "D:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "D:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "D:\Python27\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "D:\Python27\lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 10061] >

2017-05-02 11:11:23 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:11:23 luadriver.py methed:creatLuaDriver line:45 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appiumcenter\luadriver.py", line 42, in creatLuaDriver
    __global_luadriver=webdriver.Remote(luaurl, self.capabilities)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appium\webdriver\webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 185, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 247, in execute
    response = self.command_executor.execute(driver_command, params)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\remote_connection.py", line 466, in execute
    return self._request(command_info[0], url, body=data)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\remote_connection.py", line 527, in _request
    resp = opener.open(request, timeout=self._timeout)
  File "D:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "D:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "D:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "D:\Python27\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "D:\Python27\lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 10061] >

2017-05-02 11:11:23 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:11:24 luadriver.py methed:closeLuadriver line:48 INFO - close luadriver
2017-05-02 11:11:24 luadriver.py methed:closeLuadriver line:48 INFO - close luadriver
2017-05-02 11:11:24 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-05-02 11:11:24 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-05-02 11:11:25 remote_connection.py methed:__init__ line:222 INFO - Could not get IP address for host: 127.0.0.1
2017-05-02 11:11:25 remote_connection.py methed:__init__ line:222 INFO - Could not get IP address for host: 127.0.0.1
2017-05-02 11:11:26 nativedriver.py methed:creatNativeDriver line:42 ERROR - <urlopen error [Errno 10061] >
2017-05-02 11:11:26 nativedriver.py methed:creatNativeDriver line:43 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appiumcenter\nativedriver.py", line 39, in creatNativeDriver
    __global_nativedriver=webdriver.Remote(nativeurl, self.capabilities)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appium\webdriver\webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 185, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 247, in execute
    response = self.command_executor.execute(driver_command, params)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\remote_connection.py", line 466, in execute
    return self._request(command_info[0], url, body=data)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\remote_connection.py", line 527, in _request
    resp = opener.open(request, timeout=self._timeout)
  File "D:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "D:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "D:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "D:\Python27\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "D:\Python27\lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 10061] >

2017-05-02 11:11:26 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-05-02 11:11:26 nativedriver.py methed:creatNativeDriver line:42 ERROR - <urlopen error [Errno 10061] >
2017-05-02 11:11:26 nativedriver.py methed:creatNativeDriver line:43 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appiumcenter\nativedriver.py", line 39, in creatNativeDriver
    __global_nativedriver=webdriver.Remote(nativeurl, self.capabilities)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appium\webdriver\webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 185, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 247, in execute
    response = self.command_executor.execute(driver_command, params)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\remote_connection.py", line 466, in execute
    return self._request(command_info[0], url, body=data)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\remote_connection.py", line 527, in _request
    resp = opener.open(request, timeout=self._timeout)
  File "D:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "D:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "D:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "D:\Python27\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "D:\Python27\lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 10061] >

2017-05-02 11:11:26 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-05-02 11:11:26 nativedriver.py methed:getNativeDriver line:61 ERROR - global name '_NativeDriver__global_nativedriver' is not defined
2017-05-02 11:11:26 nativedriver.py methed:getNativeDriver line:62 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appiumcenter\nativedriver.py", line 58, in getNativeDriver
    return __global_nativedriver
NameError: global name '_NativeDriver__global_nativedriver' is not defined

2017-05-02 11:11:26 luadriver.py methed:creatLuaDriver line:39 INFO - creat luadriver
2017-05-02 11:11:26 luadriver.py methed:creatLuaDriver line:39 INFO - creat luadriver
2017-05-02 11:11:27 remote_connection.py methed:__init__ line:222 INFO - Could not get IP address for host: 127.0.0.1
2017-05-02 11:11:27 remote_connection.py methed:__init__ line:222 INFO - Could not get IP address for host: 127.0.0.1
2017-05-02 11:11:28 luadriver.py methed:creatLuaDriver line:45 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appiumcenter\luadriver.py", line 42, in creatLuaDriver
    __global_luadriver=webdriver.Remote(luaurl, self.capabilities)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appium\webdriver\webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 185, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 247, in execute
    response = self.command_executor.execute(driver_command, params)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\remote_connection.py", line 466, in execute
    return self._request(command_info[0], url, body=data)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\remote_connection.py", line 527, in _request
    resp = opener.open(request, timeout=self._timeout)
  File "D:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "D:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "D:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "D:\Python27\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "D:\Python27\lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 10061] >

2017-05-02 11:11:28 luadriver.py methed:creatLuaDriver line:45 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appiumcenter\luadriver.py", line 42, in creatLuaDriver
    __global_luadriver=webdriver.Remote(luaurl, self.capabilities)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appium\webdriver\webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 185, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 247, in execute
    response = self.command_executor.execute(driver_command, params)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\remote_connection.py", line 466, in execute
    return self._request(command_info[0], url, body=data)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\remote_connection.py", line 527, in _request
    resp = opener.open(request, timeout=self._timeout)
  File "D:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "D:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "D:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "D:\Python27\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "D:\Python27\lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 10061] >

2017-05-02 11:11:28 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:11:28 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:11:28 luadriver.py methed:closeLuadriver line:48 INFO - close luadriver
2017-05-02 11:11:28 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-05-02 11:11:29 remote_connection.py methed:__init__ line:222 INFO - Could not get IP address for host: 127.0.0.1
2017-05-02 11:11:30 nativedriver.py methed:creatNativeDriver line:42 ERROR - <urlopen error [Errno 10061] >
2017-05-02 11:11:30 nativedriver.py methed:creatNativeDriver line:43 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appiumcenter\nativedriver.py", line 39, in creatNativeDriver
    __global_nativedriver=webdriver.Remote(nativeurl, self.capabilities)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appium\webdriver\webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 185, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 247, in execute
    response = self.command_executor.execute(driver_command, params)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\remote_connection.py", line 466, in execute
    return self._request(command_info[0], url, body=data)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\remote_connection.py", line 527, in _request
    resp = opener.open(request, timeout=self._timeout)
  File "D:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "D:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "D:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "D:\Python27\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "D:\Python27\lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 10061] >

2017-05-02 11:11:30 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-05-02 11:11:30 luadriver.py methed:creatLuaDriver line:39 INFO - creat luadriver
2017-05-02 11:11:31 remote_connection.py methed:__init__ line:222 INFO - Could not get IP address for host: 127.0.0.1
2017-05-02 11:11:32 luadriver.py methed:creatLuaDriver line:45 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appiumcenter\luadriver.py", line 42, in creatLuaDriver
    __global_luadriver=webdriver.Remote(luaurl, self.capabilities)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appium\webdriver\webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 185, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 247, in execute
    response = self.command_executor.execute(driver_command, params)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\remote_connection.py", line 466, in execute
    return self._request(command_info[0], url, body=data)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\remote_connection.py", line 527, in _request
    resp = opener.open(request, timeout=self._timeout)
  File "D:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "D:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "D:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "D:\Python27\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "D:\Python27\lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 10061] >

2017-05-02 11:11:32 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:11:32 luadriver.py methed:closeLuadriver line:48 INFO - close luadriver
2017-05-02 11:11:32 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-05-02 11:11:47 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-05-02 11:12:20 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-05-02 11:12:20 luadriver.py methed:creatLuaDriver line:39 INFO - creat luadriver
2017-05-02 11:12:34 luadriver.py methed:creatLuaDriver line:45 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appiumcenter\luadriver.py", line 42, in creatLuaDriver
    __global_luadriver=webdriver.Remote(luaurl, self.capabilities)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appium\webdriver\webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 185, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 249, in execute
    self.error_handler.check_response(response)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\errorhandler.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: A new session could not be created. (Original error: TestBundle quit before it successfully launched)


2017-05-02 11:12:34 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:12:34 luadriver.py methed:closeLuadriver line:48 INFO - close luadriver
2017-05-02 11:12:34 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-05-02 11:12:34 nativedriver.py methed:creatNativeDriver line:42 ERROR - Message: A new session could not be created. (Original error: Requested a new session but one was in progress)

2017-05-02 11:12:34 nativedriver.py methed:creatNativeDriver line:43 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appiumcenter\nativedriver.py", line 39, in creatNativeDriver
    __global_nativedriver=webdriver.Remote(nativeurl, self.capabilities)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appium\webdriver\webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 185, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 249, in execute
    self.error_handler.check_response(response)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\errorhandler.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: A new session could not be created. (Original error: Requested a new session but one was in progress)


2017-05-02 11:12:34 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-05-02 11:12:34 luadriver.py methed:creatLuaDriver line:39 INFO - creat luadriver
2017-05-02 11:12:48 luadriver.py methed:creatLuaDriver line:45 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appiumcenter\luadriver.py", line 42, in creatLuaDriver
    __global_luadriver=webdriver.Remote(luaurl, self.capabilities)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appium\webdriver\webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 185, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 249, in execute
    self.error_handler.check_response(response)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\errorhandler.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: A new session could not be created. (Original error: TestBundle quit before it successfully launched)


2017-05-02 11:12:48 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:12:58 luadriver.py methed:closeLuadriver line:48 INFO - close luadriver
2017-05-02 11:12:58 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-05-02 11:12:58 nativedriver.py methed:creatNativeDriver line:42 ERROR - Message: A new session could not be created. (Original error: Requested a new session but one was in progress)

2017-05-02 11:12:58 nativedriver.py methed:creatNativeDriver line:43 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appiumcenter\nativedriver.py", line 39, in creatNativeDriver
    __global_nativedriver=webdriver.Remote(nativeurl, self.capabilities)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appium\webdriver\webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 185, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 249, in execute
    self.error_handler.check_response(response)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\errorhandler.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: A new session could not be created. (Original error: Requested a new session but one was in progress)


2017-05-02 11:12:58 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-05-02 11:12:58 luadriver.py methed:creatLuaDriver line:39 INFO - creat luadriver
2017-05-02 11:13:50 luadriver.py methed:creatLuaDriver line:45 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appiumcenter\luadriver.py", line 42, in creatLuaDriver
    __global_luadriver=webdriver.Remote(luaurl, self.capabilities)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appium\webdriver\webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 185, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 249, in execute
    self.error_handler.check_response(response)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\errorhandler.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: A new session could not be created. (Original error: TestBundle quit before it successfully launched)


2017-05-02 11:13:50 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:13:51 luadriver.py methed:closeLuadriver line:48 INFO - close luadriver
2017-05-02 11:13:51 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-05-02 11:14:08 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-05-02 11:14:08 luadriver.py methed:creatLuaDriver line:39 INFO - creat luadriver
2017-05-02 11:14:27 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:14:49 luadriver.py methed:closeLuadriver line:48 INFO - close luadriver
2017-05-02 11:14:56 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-05-02 11:15:08 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-05-02 11:15:08 luadriver.py methed:creatLuaDriver line:39 INFO - creat luadriver
2017-05-02 11:15:22 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:16:01 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:16:03 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:16:12 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:16:15 luadriver.py methed:closeLuadriver line:48 INFO - close luadriver
2017-05-02 11:16:18 nativedriver.py methed:closeNativedriver line:46 INFO - close nativedriver
2017-05-02 11:16:20 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-05-02 11:16:31 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-05-02 11:16:31 luadriver.py methed:creatLuaDriver line:39 INFO - creat luadriver
2017-05-02 11:16:46 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:17:23 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:17:26 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:17:32 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:17:35 luadriver.py methed:closeLuadriver line:48 INFO - close luadriver
2017-05-02 11:17:38 nativedriver.py methed:closeNativedriver line:46 INFO - close nativedriver
2017-05-02 11:17:41 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-05-02 11:17:53 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-05-02 11:17:53 luadriver.py methed:creatLuaDriver line:39 INFO - creat luadriver
2017-05-02 11:18:07 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:18:45 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:18:51 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:18:54 luadriver.py methed:closeLuadriver line:48 INFO - close luadriver
2017-05-02 11:18:57 nativedriver.py methed:closeNativedriver line:46 INFO - close nativedriver
2017-05-02 11:18:59 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-05-02 11:19:10 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-05-02 11:19:10 luadriver.py methed:creatLuaDriver line:39 INFO - creat luadriver
2017-05-02 11:19:25 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:19:35 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:19:39 luadriver.py methed:closeLuadriver line:48 INFO - close luadriver
2017-05-02 11:19:42 nativedriver.py methed:closeNativedriver line:46 INFO - close nativedriver
2017-05-02 11:33:21 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-05-02 11:33:33 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-05-02 11:33:33 luadriver.py methed:creatLuaDriver line:39 INFO - creat luadriver
2017-05-02 11:33:47 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:34:33 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:34:36 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:34:45 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:34:50 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:34:56 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:35:10 luadriver.py methed:closeLuadriver line:48 INFO - close luadriver
2017-05-02 11:35:12 nativedriver.py methed:closeNativedriver line:46 INFO - close nativedriver
2017-05-02 11:35:15 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-05-02 11:35:26 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-05-02 11:35:26 luadriver.py methed:creatLuaDriver line:39 INFO - creat luadriver
2017-05-02 11:35:41 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:36:22 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:36:22 luadriver.py methed:closeLuadriver line:48 INFO - close luadriver
2017-05-02 11:36:22 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-05-02 11:36:22 nativedriver.py methed:creatNativeDriver line:42 ERROR - Message: A new session could not be created. (Original error: Requested a new session but one was in progress)

2017-05-02 11:36:22 nativedriver.py methed:creatNativeDriver line:43 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appiumcenter\nativedriver.py", line 39, in creatNativeDriver
    __global_nativedriver=webdriver.Remote(nativeurl, self.capabilities)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appium\webdriver\webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 185, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 249, in execute
    self.error_handler.check_response(response)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\errorhandler.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: A new session could not be created. (Original error: Requested a new session but one was in progress)


2017-05-02 11:36:22 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-05-02 11:36:22 luadriver.py methed:creatLuaDriver line:39 INFO - creat luadriver
2017-05-02 11:36:43 luadriver.py methed:creatLuaDriver line:45 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appiumcenter\luadriver.py", line 42, in creatLuaDriver
    __global_luadriver=webdriver.Remote(luaurl, self.capabilities)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appium\webdriver\webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 185, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 249, in execute
    self.error_handler.check_response(response)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\errorhandler.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: A new session could not be created. (Original error: TestBundle quit before it successfully launched)


2017-05-02 11:36:43 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:36:53 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:36:53 luadriver.py methed:closeLuadriver line:48 INFO - close luadriver
2017-05-02 11:36:53 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-05-02 11:36:53 nativedriver.py methed:creatNativeDriver line:42 ERROR - Message: A new session could not be created. (Original error: Requested a new session but one was in progress)

2017-05-02 11:36:53 nativedriver.py methed:creatNativeDriver line:43 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appiumcenter\nativedriver.py", line 39, in creatNativeDriver
    __global_nativedriver=webdriver.Remote(nativeurl, self.capabilities)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appium\webdriver\webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 185, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 249, in execute
    self.error_handler.check_response(response)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\errorhandler.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: A new session could not be created. (Original error: Requested a new session but one was in progress)


2017-05-02 11:36:53 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-05-02 11:36:53 luadriver.py methed:creatLuaDriver line:39 INFO - creat luadriver
2017-05-02 11:37:24 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:38:04 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:38:11 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:38:13 luadriver.py methed:closeLuadriver line:48 INFO - close luadriver
2017-05-02 11:38:16 nativedriver.py methed:closeNativedriver line:46 INFO - close nativedriver
2017-05-02 11:42:16 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-05-02 11:42:28 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-05-02 11:42:28 luadriver.py methed:creatLuaDriver line:39 INFO - creat luadriver
2017-05-02 11:42:45 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:43:21 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:43:27 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:43:33 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:43:36 luadriver.py methed:closeLuadriver line:48 INFO - close luadriver
2017-05-02 11:43:39 nativedriver.py methed:closeNativedriver line:46 INFO - close nativedriver
2017-05-02 11:43:42 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-05-02 11:43:53 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-05-02 11:43:53 luadriver.py methed:creatLuaDriver line:39 INFO - creat luadriver
2017-05-02 11:44:08 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:44:18 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:44:24 luadriver.py methed:closeLuadriver line:48 INFO - close luadriver
2017-05-02 11:44:27 nativedriver.py methed:closeNativedriver line:46 INFO - close nativedriver
2017-05-02 11:44:29 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-05-02 11:44:40 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-05-02 11:44:40 luadriver.py methed:creatLuaDriver line:39 INFO - creat luadriver
2017-05-02 11:44:55 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:45:30 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:45:33 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:45:39 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:45:45 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:45:49 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:45:54 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:45:57 luadriver.py methed:closeLuadriver line:48 INFO - close luadriver
2017-05-02 11:46:00 nativedriver.py methed:closeNativedriver line:46 INFO - close nativedriver
2017-05-02 11:46:03 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-05-02 11:46:14 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-05-02 11:46:14 luadriver.py methed:creatLuaDriver line:39 INFO - creat luadriver
2017-05-02 11:46:29 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:47:05 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:47:07 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:47:16 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:47:22 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:47:27 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-05-02 11:47:41 luadriver.py methed:closeLuadriver line:48 INFO - close luadriver
2017-05-02 11:47:44 nativedriver.py methed:closeNativedriver line:46 INFO - close nativedriver
